on:
  push:
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '8.x'

      - name: Install dependencies
        working-directory: practice2025
        run: dotnet restore
  
      - name: Build solution
        working-directory: practice2025
        run: dotnet build --no-restore
  
      - name: Run tests
        working-directory: practice2025
        run: dotnet test --no-build
